apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  namespace: ramesh
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: manikanta1545/mani:0.0.1
        ports:
        - containerPort: 80

