apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  namespace: ramesh
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: tomcat
        ports:
        - containerPort: 80

