---
- name: Copy file to new machine
  hosts: 172.31.41.235
  tasks:
    - name: Copy file
      ansible.builtin.copy:
        src: /var/lib/jenkins/workspace/tomcat-deploy/target/devops-app.war
        dest: /home/ec2-user/apache-tomcat-10.1.23/webapps
